version: "3.1"

services:
  db:
    container_name: db
    ports: 
      - 5432:5432
    image: postgres:latest
    restart: always
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
